services:
  storybook:
    container_name: storybook
    build:
      context: .
      dockerfile: ./apps/storybook/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: ./apps/storefront/Dockerfile
      secrets:
        - source: storefront_env
          target: storefront_env
    restart: always
    ports:
      - 3002:3002
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true

secrets:
  storefront_env:
    file: ./apps/storefront/.env
