services:
  storybook:
    container_name: storybook
    build:
      context: .
      dockerfile: ./apps/storybook/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  site:
    container_name: site
    build:
      context: .
      dockerfile: ./apps/site/Dockerfile
      secrets:
        - source: site_env
          target: site_env
    restart: always
    ports:
      - 3002:3002
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true

secrets:
  site_env:
    file: ./apps/site/.env
